version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RetailThings
    ports:
      - 25432:5432